apiVersion: v1
kind: Pod
metadata:
  name: mysite-pod
  labels:
    function: app
spec:
  containers:
  - name: django
    image: ghcr.io/multifrog/cis-92:milestone-6.4
    ports:
    - containerPort: 8000
    resources:
      requests:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    env:
    - name: STUDENT_NAME
      value: "Joe Bonanno"
    - name: SITE_NAME
      value: "*"